social_pro_user:
    resource: "@SocialProUserBundle/Resources/config/routing.yml"
    prefix:   /

social_pro_main:
    resource: "@SocialProMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"